name: ultiware
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  image_picker: ^1.0.7
  camera: ^0.10.5
  photo_manager: ^3.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  country_picker: ^2.0.24
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.1.2
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
